export const FREQUENTLY_ASKED_QUESTIONS = [
  'How can I reset my password?',
  'Why am I unable to log in to my account?',
  'How can I update my account information?',
  'How do I change my email address or phone number?',
  'How can I track my order or service request?',
  'When will my order be delivered?',
  'Why was my payment declined?',
  'How can I get a refund or return a product?',
  'How do I cancel my subscription or membership?',
  'Why was I charged twice?',
  'How can I download my invoice or receipt?',
  'How do I contact customer support?',
  'Why is the application or website not working?',
  'How can I upgrade or downgrade my plan?',
  'What should I do if I forgot my username?',
  'How do I enable or disable notifications?',
  'Is my personal information secure?',
  'How can I recover deleted data or files?',
  'Why is my account suspended or restricted?',
  'What are your business hours and support availability?',
  'Can I speak with a human agent?',
  'What payment methods do you accept?',
  'How do I update my billing information?',
  'Is there a mobile app available?',
  'How do I report a bug or technical issue?',
  'Can I transfer my account to another user?',
  'How do I redeem a coupon or discount code?',
  'What is your refund policy?',
]
